"""Atlas Backend – Excel Reporter"""

from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side, numbers
from openpyxl.utils import get_column_letter
from loguru import logger


class ExcelReporter:
    """
    Generates styled Excel reports from extracted workflow data.
    """

    # Color palette
    HEADER_BG = "1E1B4B"    # Deep indigo
    HEADER_FG = "FFFFFF"
    ACCENT = "6366F1"
    ALT_ROW = "F5F3FF"
    BORDER_COLOR = "E0E7FF"

    def generate(
        self,
        data: Dict[str, Any],
        filename: str,
        title: str,
        output_dir: str,
        metadata: Dict[str, Any] = None,
    ) -> str:
        """
        Generate an Excel file from workflow output data.
        Returns the path to the generated file.
        """
        wb = openpyxl.Workbook()
        wb.remove(wb.active)  # Remove default sheet

        # ── Summary Sheet ─────────────────────────────────────────────────────
        self._create_summary_sheet(wb, title, data, metadata or {})

        # ── Data Sheets ───────────────────────────────────────────────────────
        for key, value in data.items():
            if isinstance(value, list) and value:
                self._create_data_sheet(wb, key, value)
            elif isinstance(value, dict):
                self._create_dict_sheet(wb, key, value)

        # ── Save ──────────────────────────────────────────────────────────────
        output_path = Path(output_dir) / f"{filename}.xlsx"
        wb.save(str(output_path))
        logger.info(f"Excel report saved: {output_path}")
        return str(output_path)

    def _create_summary_sheet(self, wb, title: str, data: dict, metadata: dict):
        ws = wb.create_sheet("Summary", 0)
        ws.sheet_view.showGridLines = False
        ws.column_dimensions["A"].width = 25
        ws.column_dimensions["B"].width = 40

        # Title row
        ws.merge_cells("A1:D1")
        title_cell = ws["A1"]
        title_cell.value = f"⚡ {title}"
        title_cell.font = Font(bold=True, size=16, color=self.HEADER_FG, name="Calibri")
        title_cell.fill = PatternFill("solid", fgColor=self.HEADER_BG)
        title_cell.alignment = Alignment(horizontal="center", vertical="center")
        ws.row_dimensions[1].height = 40

        # Subtitle
        ws.merge_cells("A2:D2")
        sub = ws["A2"]
        sub.value = f"Generated by Atlas Automation Platform  |  {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
        sub.font = Font(size=9, color="6B7280", name="Calibri")
        sub.fill = PatternFill("solid", fgColor="F5F3FF")
        sub.alignment = Alignment(horizontal="center")
        ws.row_dimensions[2].height = 20

        # Metadata section
        row = 4
        ws[f"A{row}"].value = "Report Details"
        ws[f"A{row}"].font = Font(bold=True, size=11, color=self.HEADER_FG, name="Calibri")
        ws[f"A{row}"].fill = PatternFill("solid", fgColor=self.ACCENT)
        ws.merge_cells(f"A{row}:D{row}")
        ws.row_dimensions[row].height = 22
        row += 1

        for k, v in metadata.items():
            ws[f"A{row}"].value = str(k).replace("_", " ").title()
            ws[f"A{row}"].font = Font(bold=True, name="Calibri", size=10)
            ws[f"B{row}"].value = str(v)
            ws[f"B{row}"].font = Font(name="Calibri", size=10)
            row += 1

        # Data summary
        row += 1
        ws[f"A{row}"].value = "Data Sheets"
        ws[f"A{row}"].font = Font(bold=True, size=11, color=self.HEADER_FG)
        ws[f"A{row}"].fill = PatternFill("solid", fgColor=self.ACCENT)
        ws.merge_cells(f"A{row}:D{row}")
        row += 1

        for key, value in data.items():
            count = len(value) if isinstance(value, list) else 1
            ws[f"A{row}"].value = str(key).replace("_", " ").title()
            ws[f"A{row}"].font = Font(bold=True, name="Calibri", size=10)
            ws[f"B{row}"].value = f"{count} record(s)"
            ws[f"B{row}"].font = Font(name="Calibri", size=10)
            row += 1

    def _create_data_sheet(self, wb, sheet_name: str, rows: List[Dict]):
        """Create a data sheet from a list of dicts."""
        safe_name = sheet_name[:31].replace("/", "-").replace("\\", "-")
        ws = wb.create_sheet(safe_name)
        ws.sheet_view.showGridLines = False

        if not rows:
            return

        headers = list(rows[0].keys())

        # Header row
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_idx, value=header)
            cell.font = Font(bold=True, color=self.HEADER_FG, name="Calibri", size=10)
            cell.fill = PatternFill("solid", fgColor=self.HEADER_BG)
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            ws.column_dimensions[get_column_letter(col_idx)].width = max(len(header) + 4, 14)
        ws.row_dimensions[1].height = 28

        thin = Side(style="thin", color=self.BORDER_COLOR)
        border = Border(left=thin, right=thin, top=thin, bottom=thin)

        # Data rows
        for row_idx, row_data in enumerate(rows, 2):
            fill_color = self.ALT_ROW if row_idx % 2 == 0 else "FFFFFF"
            for col_idx, header in enumerate(headers, 1):
                cell = ws.cell(row=row_idx, column=col_idx, value=row_data.get(header, ""))
                cell.font = Font(name="Calibri", size=10)
                cell.fill = PatternFill("solid", fgColor=fill_color)
                cell.border = border
                cell.alignment = Alignment(wrap_text=False)

        # Auto-filter
        ws.auto_filter.ref = ws.dimensions
        ws.freeze_panes = "A2"

    def _create_dict_sheet(self, wb, sheet_name: str, data: Dict):
        """Create a key-value sheet from a dict."""
        safe_name = sheet_name[:31]
        ws = wb.create_sheet(safe_name)
        ws.column_dimensions["A"].width = 28
        ws.column_dimensions["B"].width = 50

        ws["A1"].value = "Key"
        ws["B1"].value = "Value"
        for cell in [ws["A1"], ws["B1"]]:
            cell.font = Font(bold=True, color=self.HEADER_FG, name="Calibri")
            cell.fill = PatternFill("solid", fgColor=self.HEADER_BG)

        for row_idx, (k, v) in enumerate(data.items(), 2):
            ws.cell(row=row_idx, column=1, value=str(k))
            ws.cell(row=row_idx, column=2, value=str(v))
