"""Atlas Backend – PDF Reporter (reportlab)"""

from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak
)
from loguru import logger


class PdfReporter:
    """Generates professional PDF reports from workflow extracted data."""

    PRIMARY = colors.HexColor("#1E1B4B")
    ACCENT = colors.HexColor("#6366F1")
    LIGHT = colors.HexColor("#F5F3FF")
    WHITE = colors.white
    GRAY = colors.HexColor("#6B7280")
    ALT_ROW = colors.HexColor("#F9FAFB")

    def generate(
        self,
        data: Dict[str, Any],
        filename: str,
        title: str,
        output_dir: str,
        metadata: Dict[str, Any] = None,
    ) -> str:
        output_path = Path(output_dir) / f"{filename}.pdf"

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=landscape(A4),
            rightMargin=1.5 * cm,
            leftMargin=1.5 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        story = []

        # ── Cover ─────────────────────────────────────────────────────────────
        title_style = ParagraphStyle(
            "AtlasTitle",
            parent=styles["Heading1"],
            fontSize=24,
            textColor=self.PRIMARY,
            spaceAfter=8,
            fontName="Helvetica-Bold",
        )
        sub_style = ParagraphStyle(
            "AtlasSub",
            parent=styles["Normal"],
            fontSize=10,
            textColor=self.GRAY,
            spaceAfter=20,
        )

        story.append(Paragraph(f"⚡ {title}", title_style))
        story.append(Paragraph(
            f"Generated by Atlas Automation Platform &nbsp;|&nbsp; "
            f"{datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}",
            sub_style
        ))
        story.append(HRFlowable(width="100%", thickness=2, color=self.ACCENT))
        story.append(Spacer(1, 0.5 * cm))

        # ── Metadata table ────────────────────────────────────────────────────
        if metadata:
            meta_rows = [[k.replace("_", " ").title(), str(v)] for k, v in metadata.items()]
            meta_table = Table(meta_rows, colWidths=[6 * cm, 12 * cm])
            meta_table.setStyle(TableStyle([
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("TEXTCOLOR", (0, 0), (0, -1), self.PRIMARY),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [self.LIGHT, self.WHITE]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E0E7FF")),
                ("PADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(meta_table)
            story.append(Spacer(1, 0.5 * cm))

        # ── Data sections ─────────────────────────────────────────────────────
        body_style = ParagraphStyle(
            "AtlasBody",
            parent=styles["Heading2"],
            fontSize=13,
            textColor=self.WHITE,
            backColor=self.PRIMARY,
            borderPad=6,
            fontName="Helvetica-Bold",
        )
        normal = styles["Normal"]

        for key, value in data.items():
            section_title = key.replace("_", " ").title()
            story.append(Spacer(1, 0.3 * cm))
            story.append(Paragraph(section_title, body_style))
            story.append(Spacer(1, 0.2 * cm))

            if isinstance(value, list) and value and isinstance(value[0], dict):
                headers = list(value[0].keys())
                col_count = len(headers)
                page_width = landscape(A4)[0] - 3 * cm
                col_width = page_width / col_count

                table_data = [headers] + [[str(row.get(h, "")) for h in headers] for row in value]
                tbl = Table(table_data, colWidths=[col_width] * col_count, repeatRows=1)
                tbl.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), self.ACCENT),
                    ("TEXTCOLOR", (0, 0), (-1, 0), self.WHITE),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [self.ALT_ROW, self.WHITE]),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E0E7FF")),
                    ("PADDING", (0, 0), (-1, -1), 4),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]))
                story.append(tbl)
            elif isinstance(value, str):
                story.append(Paragraph(value, normal))

        doc.build(story)
        logger.info(f"PDF report saved: {output_path}")
        return str(output_path)
